.PHONY: run_streamlit generate_png generate_xlsx

run_streamlit:
	streamlit run app_streamlit.py

run_dash_personal:
	python app_dash_personal.py

run_dash_rent_applicable:
	python app_dash_rent_applicable.py
