.PHONY: run_streamlit generate_png generate_xlsx

run_streamlit:
	streamlit run streamlit/app.py

generate_png:
	python generators/generate_png_summary.py

generate_excel:
	python generators/generate_excel.py
