apiVersion: v1
kind: Service
metadata:
  name: dash-expense-tracker-service
spec:
  selector:
    app: dash-expense-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
